### ISSUE TITLE
output for lms with categorical variables

### ISSUE THREAD

**Issue by mcnulty321** [tidyverse/broom#283] opened 2018-02-21 10:55 UTC
I find dealing with the output or lms or glms when I have categorical variables very cumbersome. I've googled a little to see if others feel the same but either I'm not searching with the right terms or somehow no one else finds the output inconvenient. Seeing as broom is a package designed to make working with the output of lms or glms easier, I thought this might be a relevant place to raise the issue. So, here is an illustration of my problem:

mod = lm(qsec ~ wt + factor(am) + factor(cyl) * hp, data = mtcars)

This is what I believe to be a common way to invoke a model with categorical variables. I could have assigned the 'am' and 'cyl' variables to be factors within mtcars, however factors in data frames can be inconvenient for other reasons, and it's just quicker to run the model as I have done above. Now let's take a look at the output using broom:

tidy(mod)
![broom1](https://user-images.githubusercontent.com/36695190/36476115-d0e376d0-16f4-11e8-830c-24f8f9a82e49.PNG)

So firstly, the 'am' variable can take on values of either 0 or 1, while the 'cyl' variable can take on values of 4, 6 or 8. We notice in the output that there are no coefficients for either am = 0, or cyl = 4. The intercept term has effectively taken on the value for this combination. We could instead specify the model in this way:

mod = lm(qsec ~ wt + factor(am) + factor(cyl)*hp  - 1, data = mtcars)
tidy(mod)
![broom2](https://user-images.githubusercontent.com/36695190/36476172-fae00264-16f4-11e8-8076-5f660eeea1da.PNG)

This now gives us a term for am = 0, but the term for cyl = 4, which is implicitly zero, does not appear. While you can infer this, there are surely situations where I want to have a neat list of the adjustment for each value, but I've got to do some tedious and fiddly work to produce that list from this output, as follows:

cylCoef = coef(mod)[grep('\\(cyl\\)[^:]+$', names(coef(mod)))]
names(cylCoef) = gsub('factor\\(', '', names(cylCoef))
cylLevel = gsub('.+\\)', '', names(cylCoef))
missingCylLevel = setdiff(unique(mtcars$cyl), cylLevel)

cylCoef = c(0, cylCoef)
cylLevel = c(missingCylLevel, cylLevel)

A further inconvenience arises from the combined cyl*hp variables. The effect of hp when cyl = 6 is displayed as -0.00752, however, that is the additional effect of cyl = 6 on top of the default effect of cyl = 4, which is -0.01985. So again, if I want to see or store the effect of hp when cyl = 6, again I've got to do some work.

So I've done the work for this example, and this is what I would suggest is a more convenient and intuitively clear table summarising the coefficients:

![broom3](https://user-images.githubusercontent.com/36695190/36476264-52fa86ea-16f5-11e8-94ac-55f7573b6943.PNG)

An example of something I might want to do is add columns to mtcars which are equal to the effect of am, cyl and hp for that row. This table along with some standard dplyr code will allow me to do that quite easily. With the output from broom I displayed above, it's really quite fiddly.

Now, the code I wrote was specific to this example. I realise that to write code that will do the same more generally is much more difficult and that there are quite a lot of variations that the code would need to be able to handle. However, I'm really just looking for feedback here, am I alone in having this issue with the current output or do others see the benefit of what I'm suggesting?

**Comment by alexpghayes** [comment] 2018-06-04 21:36
The issue is that if you have a categorical predictor with `k` levels predictors and you include `k` terms (i.e. one term for each level) and an intercept, there's no longer a unique solution to the normal equations. So you have use `k-1` columns to encoded the categorical variable.

There are a couple different ways to do this. There's some references in [model.matrix](http://stat.ethz.ch/R-manual/R-devel/library/stats/html/model.matrix.html). The default behavior of `lm` can take a while to grok at first, but it is reasonable.

I'm going to close this issue, but if I come up with a better reference on dummy coding I'll definitely add it to this thread.

**Closed by alexpghayes** 2018-06-04 21:36 UTC

**Comment by antonformula1** [comment] 2018-06-20 20:08
Hi Alex,

Thanks for responding. However I'm not sure your response necessarily addresses my suggestion. I understand why there are not as many terms as their are levels when the model is fit. My issue is that if a term has been implicitly set to zero within the model, then it would be better if the output included that term with a coefficient equal to zero. Instead, it omits the term entirely from the output, which is annoying and forces the user to write that fiddly code that I gave an example of above. So my issue isn't with the underlying algorithm but with the way glm delivers the output.

**Comment by alexpghayes** [comment] 2018-06-21 16:46
The way `glm` reports coefficients for categorical variables is fairly standard. The goal is `broom` is to take the output from existing model objects and turn it into tidy `tibbles`. Adding in the coefficients that are implicitly zero in the model about isn't consistent with the `glm` output, and would be surprising to users. Additionally, we've decided (in #324) to drop rows that contain only `NA` values, which is arguably the case in the example above. So in general the behavior above isn't in line with the guarantees that `broom` makes about it's output.

At a conceptual level, there are also some things to think about if you start reporting implicitly `NA` values:
- Which coefficient appears as a zero depends on the coding of the categorical variable, and interpretations of the coefficients differ for treatment and sum codings
- Just because a coefficient is zero doesn't mean that variable level has no impact on response, so reporting it this way is misleading
- If you start reporting terms that appear appear in a model as `0 * term`, where do you stop? There are an infinite number of terms that don't appear in the model.

I hope this helps!

**Comment by mcnulty321** [comment] 2018-06-21 21:23
I get your argument about the risks of changing the behaviour in general but I'm not sure how much of a concern it would be in this scenario. You would be adding things to what's already there, the only situation I can think of where code might break is if someone has done exactly what I've done in my example, i.e. search for which levels have been dropped, only to find that none have now been dropped. I myself would happily take that pain in exchange for never having to search for the dropped levels again but I can see the other side to that argument.

In terms of your other comments concerning whether it's better to exclude levels altogether rather than include them but with a value of zero:

- you suggest that it is misleading to have a coefficient of zero because it might imply that the variable level has no impact on response. Maybe it does imply that, but surely that criticism applies equally if a term is excluded. However I'd say excluding it has the added danger of making the user unaware that extra levels even exist. So in the example I used, the user might look at the output and assume that 6 and 8 are the only values of 'cyl' present in the data. The solution I proposed in my original message, where the level appears with coefficient zero along with NAs for all the std.error/statistic/p-value fields is far more explicit in exposing the issues with the lack of a unique solution.
 - where do you stop including terms? I'm not sure I get you, surely you stop once you have all the levels of the various factors included, that is not infinite! I assume I'm misunderstanding that point...
