### ISSUE TITLE
rms tidiers do not appear to be working

### ISSUE THREAD

**Issue by nofunsally** [tidyverse/broom#279] opened 2018-02-14 18:18 UTC
I could previously use both broom::tidy and broom::glance on rms::lrm objects. Errors now arise when I try to use these commands. I am using R 3.4.2 and the most recent versions of broom and rms. Is there a way to avoid these errors?

```
broom::tidy error
Error in as.data.frame.default(x) : cannot coerce class "c("lrm", "rms", "glm")" to a data.frame
In addition: Warning message: In tidy.default(fit) :
  No method for tidying an S3 object of class lrm , using as.data.frameNo method for tidying an S3 object of class rms , using as.data.frameNo method for tidying an S3 object of class glm , using as.data.frame

```
```
broom::glance error
Error in summary.rms(x) : adjustment values not defined here or with datadist for var
```

**Comment by alexpghayes** [comment] 2018-06-04 21:43
`broom` doesn't have tidiers for `rms` models at the moment, but there is a pull request (#142) that I hope to look into soon. I'm not sure what was working before, but I don't think it was from `broom`.

Closing this issue since it's a duplicate of #30

**Closed by alexpghayes** 2018-06-04 21:43 UTC
