### ISSUE TITLE
flexibility for `augment` ?

### ISSUE THREAD

**Issue by bbolker** [tidyverse/broom#121] opened 2016-04-17 19:58 UTC
The expected use case (I think) for `augment` is to look at diagnostics, but I think there's another potential use case, which is for generating values for prediction plots.  In this case, one might want might to have a set of options for parameters such as
- fix the parameter to a single point (mean, median, or a specified value)
- expand the parameter to all of its levels (for a factor)
- expand the parameter to a regular sequence (for a continuous predictor)

`expand.grid()` could then be called to generate the values.  
- This may be related to https://github.com/dgrtwo/broom/issues/96 ...
- also worth looking at `nlme::augPred` for this, maybe `effects`, `lsmeans`, `sjPlot` packages?

Does this seem like a reasonable extension of `augment`'s functionality?

**Comment by karagawa** [comment] 2016-04-25 16:27
Agree with @bbolker!  I was about to open a discussion about `augment`. I am running couple regressions, specifically, I need to use a fixed predictor value (e.g., mean) to derive the prediction/standardization results, which is not currently supported by the `predicted values` provided by `augment`. Strongly recommend it if `augment` can be expanded. Thank you!

**Comment by hadley** [comment] 2016-06-15 15:06
I don't think `augment()` is quite the right verb for that since (in my mind, at least) `augment()` is mostly about residuals, where what you're asking for is more about predictions (since a prediction grid isn't going to have a response variable).

See also #137

**Comment by hadley** [comment] 2016-06-15 15:06
@bbolker you may also be interested in `tidyr::expand()`, `modelr::seq_range()`, and https://github.com/hadley/modelr/issues/8

**Comment by hadley** [comment] 2016-06-15 15:07
Also if you haven't already seen it, [condvis](https://cran.rstudio.com/web/packages/condvis/) provides a really nice interactive interface for exploring slices of the prediction space.

**Comment by alexpghayes** [comment] 2018-06-04 22:55
A number of `augment` methods provide a `newdata` argument. Is that sufficient for the use cases y'all are thinking about?

Not sure how many `augment` methods have a `newdata` argument though.

**Comment by alexpghayes** [comment] 2018-07-13 23:54
I don't think a new verb is necessary if you generate a grid with `tidyr::crossing` and then use list-columns and map with `~augment(.x, newdata = .y)`.

If anything, it seems like the missing piece at the moment would be a helper that would accept a data frame and then generate (one or more) interesting prediction grids. 

Closing since I don't think that would belong in broom, although happy to discuss more.

@topepo Is this something you'd be interested in for tidymodels? Neither `rsample` nor `recipes` feels quite right to me for this kind of thing. Feels vaguely similar to the domain applicability modelling stuff in APM? Maybe it belongs in a `dataspace/hyperspace` package alongside infrastructure for defining hyperparam spaces?

**Closed by alexpghayes** 2018-07-13 23:54 UTC
