### ISSUE TITLE
augment with do fails on lm(y ~ poly(x))

### ISSUE THREAD

**Issue by fja062** [tidyverse/broom#289] opened 2018-03-07 18:01 UTC
I am getting an error when I use `augment` within `do`. My quantile regression model uses `splines::bs(...)` as the predictor, but the problem can be replicated with `lm` using `poly`.  

```
library(MASS)
data(mcycle)

bind_rows(a = mcycle, b = mcycle, .id = "ver") %>%
   group_by(ver) %>% 
   do({
     fit = lm(accel ~ poly(times, degree = 2), data = .)
     augment(fit)
   })
```
> Error in bind_rows_(x, .id) : Argument 2 must be length 133, not 266

**Comment by dgrtwo** [comment] 2018-03-07 18:32
The problem is that in the augment output, the `poly(times, degree = 2)` column isn't a vector, but a 2-column matrix.

This is definitely a problem for augment in general (should we always force the output columns from model.frame() to be vectors? What kind of error could we give?) But it has a workaround in this case of giving the data argument to `augment()`, which means you get the original columns like accel and times and not a poly() matrix column:

```r
bind_rows(a = mcycle, b = mcycle, .id = "ver") %>%
   group_by(ver) %>% 
   do({
     fit = lm(accel ~ poly(times, degree = 2), data = .)
     augment(fit, data = .)
   })
```

**Comment by fja062** [comment] 2018-03-08 12:31
Ah ok, that makes sense. And the workaround works perfectly - thanks!

**Comment by alexpghayes** [comment] 2018-06-13 21:47
My take is that `augment` should add columns to original data but not keep any columns from `model.frame`. I think this specification resolves this issue, although we'll need to check that it gets enforced.

**Comment by alexpghayes** [comment] 2018-07-13 21:55
Closing in favor of #405. Eventually matrix-column support in tibbles will arrive and this will just work.

**Closed by alexpghayes** 2018-07-13 21:55 UTC

**Comment by jcdoesds** [comment] 2020-09-25 12:55
I am having difficulty seeing how to apply this solution to nested data. In that case, If I declare the augment with `data = .` or `data = .x`, I get an error. 

```
test <- mtcars %>%
  nest(data = -cyl) %>%
  mutate(
    fit = map(data, ~ lm(mpg ~ disp + poly(wt, 2), data = .x)),
    tidied = map(fit, tidy),
    glanced = map(fit, glance),
    augmented = map(fit, augment) #
  )
test %>%
  unnest(augmented) # this fails

test$augmented[1] # this works
```
