### ISSUE TITLE
Factor variables

### ISSUE THREAD

**Issue by matthieugomez** [tidyverse/broom#16] opened 2014-11-06 03:22 UTC
When the formula contains terms such as  : or , it would be nice to split term in two columns. For instance

``` R
tidy(lm(y ~ x:as.factor(z)))
```

gives

``` R
term 
(Intercept)     
x*as.factor(z):1
x*as.factor(z):2
x*as.factor(z):3
```

but it could give two supplementary columns 

``` R
term              
(Intercept)       NA   NA     
x*as.factor(z):1   x    1
x*as.factor(z):2   x    2
x*as.factor(z):3   x    3
```

This would allow to plot the estimate as a function of z, for instance.
I'm not sure what's the best way to do it that avoids regex.

**Comment by simonthelwall** [comment] 2015-02-27 13:50
I agree with @matthieugomez, I would also like to see tidy handle interactions. My current workflow is to perform the regression and then calculate stratum-specific effects with the `survey` package, for each interaction term. If this could all be wrapped up in a `tidy()` function, with exponentiation and confidence intervals, it would be much neater. 

I've got no idea how it could be achieved though. 

```r
counts <- c(18,17,15,20,10,20,25,13,12)
outcome <- gl(3,1,9)
treatment <- gl(3,3)
# print(d.AD <- data.frame(treatment, outcome, counts))

glm.D93 <- glm(counts ~ outcome * treatment, family = poisson())
#anova(glm.D93)
summary(glm.D93)

require(survey)
svycontrast(glm.D93, c("outcome2" = 1, "outcome3:treatment3" = 1))
exp(svycontrast(glm.D93, c("outcome2" = 1, "outcome3:treatment3" = 1))[[1]])
```

**Comment by nutterb** [comment] 2015-03-22 03:33
@matthieugomez, Here's a sort-of solution that gets the two columns you want using regular expressions.  Based on the common rules for variable names, I think that this will work for nearly all factor specifications because there really isn't a whole lot of transforming you can do to a factor. (I bring this up because I don't handle things like `+` and `^` in the regular expressions.  I can't think of an example where one would use such a thing with a factor)

But I'll agree with @dgrtwo that this is probably not something suited to what `broom` is trying to accomplish.  At least not in my understanding.  Also, this solution is model specific, so while `broom` can combine the results of multiple models, the code below has to be applied for each model independently.

```r
mtcars2 <- transform(mtcars,
                     am = factor(am, 0:1, c("Manual", "Automatic")))
Hmisc::label(mtcars2[, c("mpg", "am", "qsec", "wt")], self=FALSE) <- 
  c("Miles per Gallon", "Transmission", "Quarter Mile Time", "Weight")
  
fit0 <- lm(mpg ~ factor(am) * qsec + wt, data=mtcars)
tbl0 <- tidy(fit0)

makeRegex <- function(fit){
  fctr <- attributes(terms(fit))$dataClasses
  fctr <- names(fctr)[fctr == "factor"]
  fctr_regex <- paste0(fctr, collapse="|")
  fctr_regex <- gsub("[(]", "[(]", fctr_regex)
  fctr_regex <- gsub("[)]", "[)]", fctr_regex)
  fctr_regex <- gsub("[.]", "[.]", fctr_regex)
  fctr_regex <- paste0("(", fctr_regex, ")")
  return(fctr_regex)
}

fr <- makeRegex(fit0)

tbl0$level <- gsub(fr, "", tbl0$term)
tbl0$term_alt <- sapply(tbl0$term, 
                        function(x, reg){
                          x <- unlist(strsplit(x, ":"))
                          x <- ifelse(grepl(reg, x), 
                                      stringr::str_extract(x, reg),
                                      x)
                          x <- paste0(x, collapse=":")
                        },
                        fr)
tbl0

fit <- lm(mpg ~ am * qsec + wt, data=mtcars2)
tbl <- tidy(fit)

fr <- makeRegex(fit)

tbl$level <- gsub(fr, "", tbl$term)
tbl$term_alt <- sapply(tbl$term, 
                        function(x, reg){
                          x <- unlist(strsplit(x, ":"))
                          x <- ifelse(grepl(reg, x), 
                                      stringr::str_extract(x, reg),
                                      x)
                          x <- paste0(x, collapse=":")
                        },
                        fr)
tbl
```

**Comment by alexpghayes** [comment] 2018-06-04 22:04
I agree that this would be nice, but think it's out of scope for `broom` at the moment. I see `broom` as tidying `summary` methods, etc, that produce non-tidy output. Making those methods produce more useful information in the first place is hugely valuable, but not something for `broom` to take on at the moment.

As an aside, I think a there's a potential for blockbuster package if you reimagined the interface for linear models and got it right.

**Closed by alexpghayes** 2018-06-04 22:04 UTC
